artifact_uri: file:///content/mlruns/0/8a57c04fbcdf4b6980846c7b3bd118f0/artifacts
end_time: 1729988859170
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 8a57c04fbcdf4b6980846c7b3bd118f0
run_name: magnificent-skunk-89
run_uuid: 8a57c04fbcdf4b6980846c7b3bd118f0
source_name: ''
source_type: 4
source_version: ''
start_time: 1729988859159
status: 4
tags: []
user_id: root
