artifact_uri: file:///content/mlruns/0/1ea6c5dcf2074e02ad3d917ca31993d6/artifacts
end_time: 1729988900891
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 1ea6c5dcf2074e02ad3d917ca31993d6
run_name: worried-eel-81
run_uuid: 1ea6c5dcf2074e02ad3d917ca31993d6
source_name: ''
source_type: 4
source_version: ''
start_time: 1729988899915
status: 3
tags: []
user_id: root
